services:
  postgres12:
    image: postgres:12.20-alpine3.20
    container_name: postgres12
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    networks:
      - curso
    restart: always
  ms-producto-02:
    image: ms-producto:02-run
    container_name: ms-producto-02
    ports:
      - "8083:8082"
    environment:
      - URL=jdbc:postgresql://postgres12:5432/curso
      - USER_DB=postgres
      - PASS_DB=123456
      - PORT=8082
      - JAVA_OPTS=-Xms256 -Xmx900m
    networks:
      - curso
    restart: always
    depends_on:
      - postgres12
  ms-producto-03:
    image: ms-producto:02-run
    container_name: ms-producto-03
    ports:
      - "8085:8084"
    environment:
      - URL=jdbc:postgresql://postgres12:5432/curso
      - USER_DB=postgres
      - PASS_DB=123456
      - PORT=8082
    networks:
      - curso
    restart: always
    depends_on:
      - postgres12
networks:
  curso:
    external: true
