services:
  ms-producto-04:
    image: ms-producto:04
    container_name: ms-producto-04
    ports:
      - "8087:8086"
    environment:
      - URL=jdbc:postgresql://postgres12:5432/curso
      - USER_DB=postgres
      - PASS_DB=123456
      - PORT=8082
      - JAVA_OPTS=-Xms256 -Xmx900m
    networks:
      - curso
    restart: unless-stopped
networks:
  curso:
    external: true
